#!/usr/bin/env bash

set -ex

mkdir -p build && cd build

git clone --depth=1 -b rpi-4.18.y https://github.com/raspberrypi/linux.git linux-src

cd linux-src

make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig

make -j $(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
